# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require 'puppet/util/execution'

# ---- original file header ----
#
# @summary
#   Returns a file system path as escaped by systemd.
#
#
Puppet::Functions.create_function(:'openiosds::systemd_escape') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

        if (args.length != 1) then
            raise Puppet::ParseError, ("validate_cmd(): wrong number of arguments (#{args.length}; must be 1)")
        end

        path = args[0]

        cmd = "systemd-escape --path #{path}"
        escaped = Puppet::Util::Execution.execute(cmd)

        return escaped.strip

    
  end
end
